### PR TITLE
feat: add benchmarks

### PR DESCRIPTION
**Pull request by miparnisari**
Addresses https://github.com/karlseguin/ccache/issues/24

### CODE REVIEW

**Comment by miparnisari** [comment]
I don't see `atomic.Bool` defined in https://pkg.go.dev/sync/atomic@go1.18#pkg-types

How is this repo building at all? 🤔

**Comment by karlseguin** [comment]
Can the .idea folder be removed (possibly added to your `.git/info/exclude`), or if you think it's worthwhile to add for everyone, then `.gitignore`.

I think `cover.out` should also be excluded (`make c` used to remove the file)

**Comment by miparnisari** [comment]
@karlseguin i wrote the basic cases but i feel like we need more to cover more configuration scenarios

**Comment by karlseguin** [comment]
I think the next step would be to add some degree of concurrency, which is where the number of buckets would have an impact. More buckets will improve performance up to a point, at the cost of more memory.  I'm not really sure how well Go's benchmark are for this type of more complex benchmark where you aren't just testing 1 narrow behavior though.

(A few uncommon operations, e.g. `ItemCount`, `DeletePrefix, are O(N) on the number of buckets, but I don't think these are worth worrying about too much).

**Comment by miparnisari** [comment]
@karlseguin why didn't you do a squash and merge? The git commit history looks horrible 😭 Can you fix it and force push?
image

**Pull request merged**
